### ISSUE TITLE
"Loading notes" slow with lots of notes

### ISSUE THREAD

**Issue by wassname** [lexicalunit/atom-notes#11]
I've been using this for a while and have quite a lot of notes. When I search the first time after startup it takes ~30s to index available notes. I think this wait would be better removed with a cached index, or pushed the background a few seconds after startup.

**Comment by lexicalunit** [comment]
The latest version _should_ begin indexing documents as soon as the Atom editor finishes its initial activation of packages at startup time. Older versions waited to begin indexing until the user pulled up the search box.

For example, my notes take about 10 seconds to load. If I wait like 30 seconds after opening the editor to pull up the `atom-notes` search box, it comes up with documents immediately ready to search. If however I pull it up as soon as the editor starts, then I get the "indexing documents..." message.

Perhaps I can improve startup time by leveraging Atom's built in window state serialization and deserialization. This can essentially cache the search index whenever Atom exits, and then load it directly from the cache on startup.

Let me play around with this for a bit. I want to get this working faster for you (and me too!)

**Comment by wassname** [comment]
That's awesome. I just updated to the latest version and it's fast like you said. It feels fast for me now. Thanks for the great work!
