### ISSUE TITLE
Can't create note with title that is a prefix of an existing note

### ISSUE THREAD

**Issue by mshenfield** [lexicalunit/atom-notes#20]
To reproduce, create a new note with the title "1234".  Make sure it is saved, and try creating a note with the title "12". Even if you delete the helpful autocompletion, it will still open up "1234".

**Comment by lexicalunit** [comment]
Confirmed! Thanks for the report.

**Comment by lexicalunit** [comment]
Please try v1.12.2.

**Comment by mshenfield** [comment]
Awesome! Thanks for the fix!
