### ISSUE TITLE
Enhancement: Searching in notes content and not only in titles

### ISSUE THREAD

**Issue by Cutuchiqueno** [lexicalunit/atom-notes#21]
I recently switched from vim where I had a comparable notes plugin to atom. On difference to atom-notes is that in the vim plugin I was able to not only search notes titles but also the content of notes which made searches significantly more successful across notes that are years old. Of cause a challenge regarding performance exists. However, at the moment I use the fuzzy-grep plugin to be able to this and it is not particularly slow

**Comment by lexicalunit** [comment]
Thank you for noticing this! `atom-notes` was always _supposed_ to be searching by body and title, but a recent change broke this and I didn't even notice. I'm going to fix this and add some spec tests to ensure we don't have a future regression on this issue.

**Comment by lexicalunit** [comment]
Alright, give v1.14.0 a try!

**Comment by Cutuchiqueno** [comment]
works like a charme. Thx. for the such immediate reaction!
