### ISSUE TITLE
Toggle Atom Notes does not proceed past "Loading Notes"

### ISSUE THREAD

**Issue by jmroland** [lexicalunit/atom-notes#27]
When I toggle atom notes it does not display a list or allow searching. If I type in the name of an existing note and hit enter, it will open the note. If I type in the name of a non-existing note and hit enter, it will create a new note (all in the correct directory). However typing does not bring up a list of search results.

![image](https://user-images.githubusercontent.com/10378631/37006135-d1989e34-208b-11e8-857f-241b17273484.png)

**Comment by lexicalunit** [comment]
There is an issue with directories containing lots and lots of notes. Because `atom-notes` has to index everything on load (and if the data is too big to be serialized, on every single start up), it can take a while to work through a directory with a ton of data in it. How many megabytes do you have in your notes directory, @jmroland?

**Comment by jonszcz** [comment]
I'm finding the same issue here. This worked not too long ago, but has not been indexing in the past few days. My notes directory is only 8.55MB.

Is it possible that non-markdown/text documents are causing the index to hang?

**Comment by lexicalunit** [comment]
@jonszcz Yah, 8.55MB should load in a fraction of a second.

I actually noticed this same issue myself just the other day. I killed Atom and then re-opened it. After that it seemed to work fine again. I'm not sure what is going on here...

**Comment by lexicalunit** [comment]
Found the bug! Give v1.16.1 a try.

**Comment by jonszcz** [comment]
That fixed it for me! Thanks so much for the quick reply!

**Comment by jmroland** [comment]
I just wanted to add my thanks for the fast responses. This is package a dream come true on Windows.
