### ISSUE TITLE
Porting notational-velocity-like atom-notes to VSCode

### ISSUE THREAD

**Issue by robwalton** [lexicalunit/atom-notes#29]
For some reason I've switched to vscode. The one thing I'm really missing is atom-notes. I'm looking into creating a package with the same functionality. I would of course mention atom-notes loudly in any documentation! 

It would be nicer to share code with atom-notes rather than copying it; possibly by pulling the core note-handling functionality into a package. It would add some complexity to atom notes.  **Does the atom-notes community have any interest in this?**

At first glance the code with a good ratio of functionality to atom API code is:

* `interlink.js`
* `notes-fs.js`
* `notes-store.js`
* `notes-view-list.js`

**Comment by robwalton** [comment]
Great, I'll see how it goes. I'll start by working in atom-notes to pull out the 'backend' type code into a package. To keep things simple I'll let it pull in config from whichever of atom or vscode is available.

On the vscode front... The first issue is that the only thing that looks usable in vscode is a QuickPick list. It does the search for you, but you need to transfer all the file names a _and_ file contents for it to search. I tested this with dummy data with 1000 items each with 20 paragraphs of text  (totalling ~10000 characters per item). The speed was fine; but it does limit search options: it seems to:

1. match only within the field I'm using for the file name _or_ the the one I'm using for the text,
2. only match forwards,
3. only fuzzy search across word boundaries

I think it should be good to go though!

**Comment by robwalton** [comment]
I've just realised that vscode's QuickPick list won't return anything but an item from the list; so it can't return the search string so we can use it to make a new note. That might put an end to this project for now, unless vscode supports another way of extending things. I can't see another way of extending vscode that would work though. There are currently 81 [open issues labelled quick-pick](https://github.com/Microsoft/vscode/labels/quick-pick) so it would requires some strong will to get this added I imagine! There seems to be one [meta-ticket](https://github.com/Microsoft/vscode/issues/45589) indicating the developers are considering enhancing it.

Ahh, and it won't autofill the search field either with the best match; which would slow adding new notes into a hierarchy down.

**Comment by robwalton** [comment]
Hi @lexicalunit, looks like this project is paused indefinitely. Feel free to close this ticket so it doesn't clutter up your issues list!

**Comment by lexicalunit** [comment]
Thanks @robwalton! Hopefully one day this will be possible in VS Code.

**Comment by robwalton** [comment]
Agreed, would be good. Vscode feels more solid and I like the settings file for configuration. Back to atom for atom-notes it is.

**Comment by rajalokan** [comment]
Landed here after looking for atom-notes replacement in VSCode. Good to see I'm on correct path of using VSCode. 

If anyone can check if now can it be done or any similar package in vscode marketplace. TIA
