### ISSUE TITLE
Missing settings and does not launch

### ISSUE THREAD

**Issue by philip-hodder** [lexicalunit/atom-notes#3]
I tried this on my work laptop this morning and it all worked OK. However, this evening on my Mac I only get the "Atom Notes Grammar" section of the Settings - I can't set the save location, for example. I also get "no match found" when I try to run "atom-notes:toggle", even after restarting Atom. Am I doing something wrong?

**Comment by lexicalunit** [comment]
Something's definitely wrong! I wonder what it is... 🤔

**Comment by philip-hodder** [comment]
I did seem to fix it: I noticed a bug icon on the status bar, clicked that and rebuilt something. Then it worked OK, although there are still two instances of the 'grammar' section. But it does work now!

**Comment by lexicalunit** [comment]
Ah! Yes that. I should add some documentation about that. There's a dependency of Atom Notes that has to be compiled for each specific version of Atom. So if Atom does an automatic in the background when you restart it, that can cause a bug that will force you to recompile the modules. It's a bit frustrating, _sigh_.

**Comment by philip-hodder** [comment]
Well, it's working OK now!
