### ISSUE TITLE
notes disappeared

### ISSUE THREAD

**Issue by piccolbo** [lexicalunit/atom-notes#30]
For some reason I had to reinstall most of my atom packages. After that, when I toggle atom-notes shows an empty list. I configured it to use the right directory and there are three files in there. Suggestions?

**Comment by lexicalunit** [comment]
If you go to that directory are your notes there? It's just that `atom-notes` isn't seeing them correctly?

**Comment by piccolbo** [comment]
Yes, that's what I meant by 
> there are three files in there

Not random files, but exactly the three notes I took. Sorry to be unclear. It's only in atom-notes that they are missing.

**Comment by piccolbo** [comment]
The notes reappeared. Let's chalk it up to a temporary decay of atom into subatomic editors. Thanks
