### ISSUE TITLE
Create URI scheme to toggle notes view from outside Atom

### ISSUE THREAD

**Issue by robwalton** [lexicalunit/atom-notes#31]
It would be handy to toggle the notes view from outside Atom. For example with a system-wide keyboard shortcut via macOS' [Alfred](http://www.alfredapp.com/) or [LaunchBar](https://www.obdev.at/products/launchbar/index.html). Atom handles local URL schemes of the form `atom://package-name/...`. These can then be triggered from macOS or Windows.

(Pull request on the way)

**Comment by lexicalunit** [comment]
Sounds cool!

**Comment by lexicalunit** [comment]
Resolved by #32!
