### ISSUE TITLE
Notes list shows externally added files with wrong extensions and hidden files

### ISSUE THREAD

**Issue by robwalton** [lexicalunit/atom-notes#33]
I have the atom-ctags extension installed. This automatically creates `.tags` files in my notes directory which then show up in the notes view. As an experiment I also manually added files with the wrong file extension in there too and those also show up.

In the code:
`notes-fs.isNote()` seems to exclude these files
`notes-store.setUpFileWatcher()` adds all files regardless of file extension to the NotesStore

I'll make a pull request, but I'm not confident in this area of the code.

**Comment by lexicalunit** [comment]
No worries, I can review your PR too :)

**Comment by lexicalunit** [comment]
Resolved by #32!
