### ISSUE TITLE
Use markdown-writer keymappings in atom-notes

### ISSUE THREAD

**Issue by sati-bodhi** [lexicalunit/atom-notes#43]
When trying to use `markdown-writer` shortcuts such as 'cmd-i' for italics, `atom-notes` turns up this error: 

![default](https://user-images.githubusercontent.com/7592695/40555928-4e7d83ca-607d-11e8-997f-62762a658a11.png)

Is it possible to integrate `markdown-writer` functions into `atom-notes` without switching the grammar? ('cmd-i' works fine when grammar is switched to markdown or pandoc-markdown)

**Comment by lexicalunit** [comment]
I believe we could support this easily via `language-atom-notes` if the `markdown-writer` plugin made [this code](https://github.com/zhuochun/md-writer/blob/master/lib/config.coffee#L22) configurable. We just want to add `source.gfm.notes` to that list. If they made that code configurable in their package settings, you could add it yourself. Sadly it appears that the `markdown-writer` plugin doesn't allow people to edit that setting, currently.

When I get the chance I can do some testing to confirm that adding `source.gfm.notes` to that list will resolve your issue. Then I may open a PR against `markdown-writer` to make that list configurable for them.

If you're ok mucking about in source code you could try adding `source.gfm.notes` to that list on your local copy of the package source.

**Comment by sati-bodhi** [comment]
It works, thanks!
