### ISSUE TITLE
Only the URI atom://atom-notes/toggle is currently supported.

### ISSUE THREAD

**Issue by MaxPower9** [lexicalunit/atom-notes#45]
When launching notes from outside atom with 
`open atom://atom-notes/toggle`
It works, but I also get a toaster message "Only the URI atom://atom-notes/toggle is currently supported."  
If instead I use: 
`open atom://atom-notes/toggle/preview` 
It works with no error.  Not sure what's going on here.

**Comment by lexicalunit** [comment]
Weird. That error message is wrong tho so I'm going to fix that. While I'm at it I refactored the code a bit which might help fix this issue.

**Comment by lexicalunit** [comment]
@MaxPower9 v1.19.2 works for me, let me know if it works for you.

**Comment by MaxPower9** [comment]
Yup, it works now.
