### ISSUE TITLE
Concurrent changes and conflicts in atom-notes

### ISSUE THREAD

**Issue by piccolbo** [lexicalunit/atom-notes#46]
Hi, in the tutorial you recommend syncing with dropbox to share notes among multiple devices. I've done that in the past with notational velocity, and it was a source of problems to no end. Even if I was the only person editing my notes, they appeared to be edited concurrently from multiple devices and therefore multiple forked copies (conflicted copies in dropbox jargon) were created, with no support for merging them. I think this is caused by dropbox only syncing at certain intervals, say hourly, thus making concurrent updates by one person possible, or at least I have no other theory. I was wondering anyone observed this with atom-notes and if there is a better solution.

**Comment by lexicalunit** [comment]
I haven't noticed an issue myself but then in my case I mostly use `atom-notes` from one computer and only occasionally use it from two others. So my use case here probably wouldn't expose the kind of issue you mentioned.

**Comment by piccolbo** [comment]
Alright thanks
