### ISSUE TITLE
Interlinking not working with language-atom-notes

### ISSUE THREAD

**Issue by OSoG** [lexicalunit/atom-notes#54]
Hi, I love atom-notes.
But I haven't figured out interlinking, and it seems it doesn't work..
language-markdown,
language-atom-notes 0.4.1
are all  installed.
What can I do?

**Comment by OSoG** [comment]
Nevermind. I just found out that it actually works!!! ^^;
But it works only for atom-notes.
Maybe it will be GREAT if we can access atom-notes files in any textfiles(files that are not notefiles)
Thank you for AWESOME package and Please tell me if you plan for any development regarding my suggestion.

**Comment by lexicalunit** [comment]
@OSoG Good idea! Give v1.20.0 a try.
