### ISSUE TITLE
Is it possible to change the grammar of Notes?

### ISSUE THREAD

**Issue by jkamenik** [lexicalunit/atom-notes#56]
I tried to switch from `language-gfm` to `language-markdown` as it has better rendering, or at least better parsing of markdown elements.  However, this plugin always makes the source `source.gfm.notes` and I cannot figure out how that is forced.

Right now any file that is `.md` opens as scope `text.md` except ones opened by Atom Notes.  I can manually switch the grammar after opening and get the benefit of the new rendering, but then it lacks the inner file linking.

I am not sure how to get the best of both world.  If you point me the direction of how the `gfm` source is forced then I can see if I can fix and submit a PR

**Comment by lexicalunit** [comment]
Do you also have `language-atom-notes` installed? If you do, then that's what's doing it I think. You shouldn't need `language-atom-notes` to be installed anymore. I've made changes to `atom-notes` so that `language-atom-notes` is entirely optional and probably isn't worth installing at all.

**Comment by jkamenik** [comment]
I did have `language-atom-notes` installed.  Disabling it fixes the issue.  Thanks.
