### ISSUE TITLE
Interaction with others packages (markdown-writer)

### ISSUE THREAD

**Issue by lakonis** [lexicalunit/atom-notes#9]
Hello,
it seems that atom-notes doesn't work with other packages like [markdown-writer](https://atom.io/packages/markdown-writer) for instance, but would work with markdown-preview. 
I wonder if there is a workaround to make atom-notes md files working with other packages.
Thanks !

**Comment by lakonis** [comment]
Workaround in [issue 8](https://github.com/lexicalunit/atom-notes/issues/8)

**Comment by wassname** [comment]
I think you want normal markdown grammar so you can use the features of markdown writer with atom-notes. Well so do I, and here's my dirty workaround. Set the grammar to markdown 1 second after the file has loaded by putting this in your `init.cs`/

```coffee
# See https://github.com/lexicalunit/atom-notes/issues/9
extname = require('path').extname
fileTypes = '.md': 'text.md'
nullGrammar = atom.grammars.selectGrammar('text.plain.null-grammar')
atom.workspace.observeTextEditors (editor) ->
  grammar = undefined
  grammar = atom.grammars.selectGrammar(fileTypes[extname(editor.getPath())])
  console.log 'setting lang', grammar, editor.getGrammar()
  # atom notes seems to set language on open, since callback set in init.cs
  # are first we need to set it back after a delay
  if grammar != nullGrammar
    setTimeout (->
      editor.setGrammar grammar
      return
    ), 1000
  return
```

**Comment by lexicalunit** [comment]
I think I'm gonna make a change so the next version of `atom-notes` uses the standard Markdown grammar instead of it's own special flavour. It will make things so much simpler in a lot of ways and we'll get the benefits of packages that add features to Markdown files without any hassle.

**Comment by lexicalunit** [comment]
Reopening issue until ☝️ is done.

**Comment by lakonis** [comment]
Thanks @wassname , however [this solution (issue8)](https://github.com/lexicalunit/atom-notes/issues/8) works fine for me, which I found a bit better than running a script each time a file is loaded..
@lexicalunit what are the difference in the two grammars ? Maybe @seongjaelee made some relevant choice ?

**Comment by lexicalunit** [comment]
@lakonis the special grammar allows us to give some syntax highlighting to interlinks. Like this:

<img width="441" alt="screen shot 2017-09-04 at 8 42 37 pm" src="https://user-images.githubusercontent.com/1903876/30041708-eb32f5ce-91b1-11e7-9963-b3bf96d51ef6.png">

But I dunno... that's not that important when you could have much stronger interoperability with Markdown relevant packages like `markdown-preview` and others.

**Comment by lakonis** [comment]
Thanks for the quick move !
It might be a personal perception, but loosing the highlighting on Atom Notes main feature (interlink) doesn't seem coherent with the usage people could expect. I understand interlinks will still work the same, but for users like me linking notes massively, the hightlighting is quite precious.

**Comment by lexicalunit** [comment]
I think in the next version I'll have it be optional so users can pick if they want to use the Atom Notes grammar with syntax highlighting if they want, or use the Markdown grammer if they would rather.

**Comment by lexicalunit** [comment]
@lakonis To support syntax highlighting of interlinks I created [`language-atom-notes`](https://github.com/lexicalunit/language-atom-notes) which is supports in version 1.10.0 of `atom-notes` 🎉

**Comment by lakonis** [comment]
Beautiful! thanks a lot for taking this in consideration :)
:heart_eyes:
